name: publish

on: [push]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          docker build --build-arg HTTP_PROXY=$HTTP_PROXY --build-arg HTTPS_PROXY=$HTTPS_PROXY --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy --network host -t ghcr.io/zephyre777/netopeer2-ietf120:v1.0 ${{ github.repository }}/.github/workflow
          docker run ghcr.io/zephyre777/netopeer2-ietf120:v1.0
          docker push ghcr.io/zephyre777/netopeer2-ietf120:v1.0
